### ISSUE TITLE
Making requests at deployed app page

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#23]
**Steps:**
1. Log in
2. Read profile (repeat 10 times)

**Behavior:**
- in repeatedly executing read profile, i get randomly varying responses between `User not logged in` and actually getting user's profile

**Comment by ralf-t** [comment]
try hardcoding the secret key

**Comment by Iionsroar** [comment]
the problem indeed seems to be this part in the config file:
```python
SECRET_KEY: str = secrets.token_urlsafe(32)
```

will close the issue once a fix is created and merged to main

**Comment by Iionsroar** [comment]
feature suggestion: command that can generate secret key and put it to clipboard

**Comment by Iionsroar** [comment]
im good iwth that
