### ISSUE TITLE
Question type

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#26]
- add field that identifies whether an item is a `multiple-choice` type or `fill-in-the-blank` type

**Comment by Iionsroar** [comment]
**suggestion 1 - new fields:**  question-type & answer
- what if there are multiple answers accepted? make answer field a list type (?)

**suggestion 2 - new field**: question-type only
- same mechanic as multiple-choice type (question is related to answer objects) but renders differently on the frontend

**Comment by ralf-t** [comment]
IIRC ang napagkasunduan natin, dadaggdagan lang ng question type yung question para yun na lang pagbabasehan kung ano marerender sa frontend (with choices for multiples choice, without choices for fill in the blanks)

Meaning we're going w/ suggestion 2

Correct me if im wrong

**Comment by ralf-t** [comment]
Also this means wala na tayong additional schemas no? Gagamitin nalang yung multiple choice for both types of question

**Comment by Iionsroar** [comment]
yep, iniba na lang yung process sa pag check ng answers
