### ISSUE TITLE
Storing input device data

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#31]
### **Describe the aim of this enhancement**

Create a method for storing input device data as part of the cheating detection feature of our thesis project. 

### To Do

- [x] Add model for input device data/ action data/ event data
    - [x] Fields: quiz_id, student_id, attempt_id, question_id, timestamp, blur, focus, copy, paste, left-click, right-click, double-click
    - [x] Add validator: only a single action field must have the value 1, the rest is 0 (if cant make work with pydantic, just modify create method) [gd](https://github.com/samuelcolvin/pydantic/discussions/4289) [so](https://stackoverflow.com/questions/73167358/how-do-i-write-a-validator-that-checks-whether-a-record-has-only-a-single-field)
    - [x] remove quiz_id and student_id (can be accessed via attempt obj)
- [x] Add CRUD methods
    - [x] Add CRUD methods for summarizing quiz actions
    - [ ] Add method for exporting quiz actions from database
        - adds csv to `/data`, which is ignored by git
        - method is called when submitting quiz (?)
- [x] Add factory
    - [x] Modify create method to adjust other action fields' values depending on input action
- [x] Add CRUD tests
    - [x] Test single-action validator
    - [x] Test read methods
    - [x] Test factory
        - [x] Discover bug where actions is equal to [0,0,0,0,0,0,0] when randomized action is [0,0,0,0,1,0,0] (where `copy_ ` is 1)
            - Finding: it is because of the `NameError: Field name "copy" shadows a BaseModel attribute; use a different field name with "alias='copy'"`
- [x] Add endpoints for creating and reading input device data
    - [x] Update create endpoint to only store 1 quiz action instead of storing bulk actions for any given question
- [x] Add API tests
    - READ ACTIONS OF ALL PARTICIPANTS AT GIVEN QUESTION
    - READ ACTIONS OF ALL PARTICIPANTS AT GIVEN QUIZ
    - READ ACTIONS AT GIVEN ATTEMPT QUIZ
    - READ ACTIONS AT GIVEN ATTEMPT QUESTION
- [x] Add actions to initial data 

### Alternatives to be considered
- [Use enum for action/ event types](https://stackoverflow.com/questions/73167358/how-do-i-write-a-validator-that-checks-whether-a-record-has-only-a-single-field/73167843#73167843)

**Comment by ralf-t** [comment]
Setup tayo quick meeting for dis?

**Comment by Iionsroar** [comment]
Updated index comment as per quick discussion with team

**Comment by Iionsroar** [comment]
@ralf-t csv yung preferred input sa ML diba 
bale need naten ng method to export from db to csv?

**Comment by ralf-t** [comment]
oh shee forgot to reply here

oo ata? pero either way madali lang naman palitan format but lezz go csv lol

every action kasi what if nag exit siya bigla huhu all data lost

**Comment by Iionsroar** [comment]
> every action kasi what if nag exit siya bigla huhu all data lost

ohh nakalimutan ko iconsider to, update ko code maya

**Comment by ralf-t** [comment]
Sa data cleaning nalang ng ML i aggregate yung mga action kaya yung mga raw data natin na kalalabasan ay rows of

0 0 0 0 1 0 0 0 0 
0 0 0 1 0 0 0 0 0
1 0 0 0 0 0 0 0 0 

right kasi stored every event triggered

**Comment by Iionsroar** [comment]
yep
