### ISSUE TITLE
Add endpoint for getting results of the quizzes authored by a teacher

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#32]
### **Describe the aim of this enhancement**
When the API is used with [kweeznuts](https://github.com/xtian18/kweeznuts), it can be observed that the frontend makes multiple GET requests in order to render the `Reports` page of the logged in teacher. This enhancement will allow the client to instead make a single request and hopefully lighten the load especially on a PostgreSQL server.

- backend server
    ![image](https://user-images.githubusercontent.com/65220389/180809462-461f3c37-60e5-4500-b888-bd783391aec5.png)
- client (both the `My Quizzes` and `Reports` pages display a list of the quizzes authored by the logged in teacher, yet the latter still makes multiple requests, as seen in the backend logs above)
    ![image](https://user-images.githubusercontent.com/65220389/180809317-169ccbc6-9eb8-419e-9252-7e20fef4f805.png)
    ![image](https://user-images.githubusercontent.com/65220389/180809328-06c59705-ee02-4af6-89d9-b6fc0c8e716b.png)

### **Describe the solution you'd like**
Similar to the `GET /quizzes/` endpoint, write a path operation for accessing the results of the quizzes authored by a teacher

**Comment by ralf-t** [comment]
G lang ako

Pero atm, I dont think priority natin ang performance ng web app since hohost lang naman natin for a limited amount of time? Kaya for me, ok lang kahit di efficient algos.

What do you think?

**Comment by Iionsroar** [comment]
agree

pero since naadd ko na yung code merge ko na rin xDD

update ko yung ibang items mamaya, basta concern ko lang yung maging smooth ang transactions ng user with d app
