### ISSUE TITLE
Same-site lax

### ISSUE THREAD

**Issue by ralf-t** [Iionsroar/inquizitor#43]
**To Do**
- [ ] Remove localhost URLs from allowed origins at production, after production frontend is tested

**Describe the bug**
Token is not being set because it is blocked due to same-site=lax attribute. Meaning hindi rin ata nababasa ng configs nang maayos.

**To Reproduce**
1. Replace all the fetch requests url in the frontend to point to the backend in heroku (http://localhost:8000 convert to https://inquizitor-ai.herokuapp.com)
2. Run the frontend
3.  Try logging in

**Expected behavior**
The token must be set when you look at the application cookies.

**Screenshots**
![image](https://user-images.githubusercontent.com/66364379/186423257-8407d9b4-adf3-4177-a92f-a465646e326d.png)
![image](https://user-images.githubusercontent.com/66364379/186424241-33ed7160-199d-482f-a4b5-e3e6fdb67ef4.png)
![image](https://user-images.githubusercontent.com/66364379/186423368-b3f889d7-204d-4ea9-8ad9-efc5f45e6148.png)

**Additional context**
This is a backend problem. The request is successful pero hindi naseset yung token in the frontend dahil may config bug in the backend

**Comment by Iionsroar** [comment]
not sure what fixed the issue but the following were done:
1. add the following to heroku workflow env var
```sh
FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
```
2. include localhost to allowed origin _for testing_
![image](https://user-images.githubusercontent.com/65220389/186437848-3af4e175-dec6-4c66-84a6-5e31ed73a76d.png)
3. update all `os.environ.get` calls to `os.getenv`

special thanks to the prior and new testing done to get to the root of the rabbit hole

**Comment by Iionsroar** [comment]
copy

**Comment by Iionsroar** [comment]
removed localhost from prod env origins
