### ISSUE TITLE
Deploy to Azure

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#44]
**Describe the aim of this enhancement**
Deploy to Azure and (optional) add to workflow.

**Describe alternatives you've considered**
- [ ] AWS
- [ ] Google
- [ ] IBM
- [ ] Oracle
- [ ] https://www.netlify.com/
- [ ] https://sourceforge.net/

**Comment by Iionsroar** [comment]
- AWS (cannot proceed with free trial)
![image](https://user-images.githubusercontent.com/65220389/187212514-7e91651c-f280-41d4-8744-1a3cd49f4fec.png)
![image](https://user-images.githubusercontent.com/65220389/187212583-cd02c816-6702-43fc-8125-f38ee3dd83f7.png)
- IBM (cannot proceed with free trial)
![image](https://user-images.githubusercontent.com/65220389/187212633-a4115cf8-22aa-4c4d-b58b-8f882b4942fd.png)

**Comment by ralf-t** [comment]
I say settle muna sa Heroku and avail nalang ilang months ng subscription. Pag naman nag gather tayo ng data i doubt tatagal isang buwan yon

Azure is always there din naman if shit hits the fan

**Comment by Iionsroar** [comment]
g
