### ISSUE TITLE
Storing Input Device Data: Frontend Findings

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#45]
**Describe the aim of this enhancement**
Discuss the findings/ discoveries presented at https://github.com/Iionsroar/inquizitor/pull/40#issuecomment-1229499334:
> * some things na napansin ko while working sa input events:
>   
>   * pag gumamit ng double click event, naccount nya yung double click at yung unang left click. nakita kong solution ay isimulate yung double click gamit time interval ng clicks. altough tatry ko pa kung may mas okay na solution
>   * ang naging problem sa gantong setup ay narerecognize nya ring double click kahit sa magkaibang lugar nagclick nang dalawang beses basta within the timeframe (500ms). normally kasi ata, dapat marecognize lang na double click kapag nasa iisang location yung magkasunod na click
>   * sakop ng copy at paste event yung keyboard shortcut at yung nasa context menu pag nag right-click
>   * unlike other events na buong page ang sakop, nakaspecific lang yung paste event sa textbox pag fill-in-the-blank kasi dun lang sya pwede matrigger

**Comment by ralf-t** [comment]
- @xtian18 re single vs double click, na try mo na to?

https://stackoverflow.com/questions/48295288/how-to-handle-single-click-and-double-click-on-the-same-html-dom-element-usi


- Oh good to know yung sa copy and paste
- re paste event, makes sense naman no? Kasi dun lang naman talaga natin idedetect sa quiz?
- To clarify, yung "buong page" na tinutukoy mo ay yung entire tab no?

**Comment by xtian18** [comment]
* @ralf-t medyo similar yung ginagamit ko kasi may settimeout din
* yung buong page ay yung buong html page lang so within the tab pero d kasama yung address bar sa taas

**Comment by ralf-t** [comment]
- Pwede makita yung code? Baka makatulong
- Yeah thats good

**Comment by xtian18** [comment]
* Ito yung container sa buong page with events
![image](https://user-images.githubusercontent.com/58137485/187359087-11684450-9bd8-45a6-bbbf-e8f9840a844e.png)
* Ito yung function na naghahandle ng both left click at double click. Yung is_taking ay boolean lang para magsend lang ng input device data pag currently taking ng quiz lang. Yung counter ay 0 sa umpisa.
![image](https://user-images.githubusercontent.com/58137485/187359325-85ff9481-4002-4666-9c4b-f9532243d4c8.png)
* Ito yung function para sa mismong pagsesend ng data sa server.
![image](https://user-images.githubusercontent.com/58137485/187359493-be3d0ad4-f3af-476a-93c2-c292c6818e4f.png)

**Comment by ralf-t** [comment]
Fast solution ay i subtract nalang sa data processing yung total of double clicks sa aggregated left clicks. But that wouldnt look good sa logs HAHAHAHAHAHA
