### ISSUE TITLE
Access to API has been blocked by CORS policy

### ISSUE THREAD

**Issue by xtian18** [Iionsroar/inquizitor#46]
This error shows up when accessing the prod backend from the prod front-end https://inquizitor-webapp.herokuapp.com
![image](https://user-images.githubusercontent.com/58137485/187961155-772f298f-8cc8-4f3c-b766-956499c97f9e.png)

**Comment by Iionsroar** [comment]
Added the new frontend url/ origin to the prod backend accepted origins, can now access
