### ISSUE TITLE
Add Test Items to be Used in Building the Dataset

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#47]
**Describe the aim of this enhancement**
Add test items for building the dataset

**Describe the solution you'd like**
- [x] Get the original document
- [x] Add command to generate quiz from json/txt file
- [x] Add command option to seed quiz taking data for the above quiz 

**Archived**
- Add the test items extracted from the above document to a json file
```json
{
  "items": [
    {"question": "",
    "question_type": "",
    "correct_answer": "",
    "incorrect_answers": [""]}
  ]
}
```

**Comment by Iionsroar** [comment]
@ralf-t @xtian18 @XSeed21 @jebjebs anong set gagamitin naten sa data gathering

from `CCS 4980 - CHAPTERS 1-3.gdoc`
![image](https://user-images.githubusercontent.com/65220389/188062032-fc5482e8-8eae-4ed2-8c17-decb9c49a348.png)

from `2nd sem thesis.gdoc`
![image](https://user-images.githubusercontent.com/65220389/188062134-60b97fc9-342f-43ef-bc2f-358ae5067cd6.png)

**Comment by ralf-t** [comment]
Set? I thought iisang exam lang ginawa naten na ipagagamit for all participants?

**Comment by Iionsroar** [comment]
by set i mean yung lumang set ba or yung bago/ updated

**Comment by ralf-t** [comment]
Kung ano siguro napasa natin sa panel 😖 Di ko knows yung bago sry

**Comment by Iionsroar** [comment]
oks hanapin ko lang yung original docu
