### ISSUE TITLE
Request has been blocked | API Redirects to HTTP on GET /quizzes, POST /quizzes, GET /users, POST /users because of Missing Trailing Slash

### ISSUE THREAD

**Issue by xtian18** [Iionsroar/inquizitor#48]
Gumagana yung ibang route like login at get profile, pero yung iba like get quizzes at signup ganto nirereturn. Gumagana rin ata yung get specific quiz kasi pag inaaccess ko directly sa address bar naoopen naman. So d ako sure alin pang routes ang may error na ganto.

Nag-console log na rin ako nung sample API URL na nirerequest and tama naman na https ginagamit pero sabi sa error http daw?
Chineck ko lahat naman ginagamit yung ng dynamic URL sa config file na may https. Di ako sure kung sa front-end and error or backend, baka may idea kayo.
![image](https://user-images.githubusercontent.com/58137485/188086571-51e9f077-43c2-4114-bd75-6179ca56603b.png)

**Comment by Iionsroar** [comment]
pag nilog sa console yung `process.env.BASE_URL` ano lumalabas

**Comment by xtian18** [comment]
> pag nilog sa console yung `process.env.BASE_URL` ano lumalabas

/

**Comment by Iionsroar** [comment]
not sure pa ano problema pero tingin ko frontend siya tas vue router yung cause ng error

@ralf-t naencounter mo na ba to

**Comment by Iionsroar** [comment]
baka related

![image](https://user-images.githubusercontent.com/65220389/188113435-65a381d6-419e-4b5c-9b50-426436e823b0.png)
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307
- https://developer.mozilla.org/en-US/docs/web/http/headers/location

**Comment by Iionsroar** [comment]
wait wag muna pala may itatry lang ako

**Comment by Iionsroar** [comment]
patry rin neto (w/o doing yung above)

add snippet to index.html
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

**Comment by xtian18** [comment]
gumagana na sya

**Comment by Iionsroar** [comment]
> add snippet to index.html

gamit to?

**Comment by ralf-t** [comment]
Oh yayyyy. Anything else?

Was gonna suggest na mag letsencrypt lol

**Comment by Iionsroar** [comment]
g lang letsencrypt

**Comment by ralf-t** [comment]
But gumagana naman na kamo eh

**Comment by Iionsroar** [comment]
yep pero patch lang siya, if may ibang frontend na coconnect, sila yung need magadjust

i-close as not planned ko na lang to para madaling balikan if ever
