### ISSUE TITLE
Discuss Free Heroku Postgres Row Limit

### ISSUE THREAD

**Issue by Iionsroar** [Iionsroar/inquizitor#53]
**Describe the aim of this enhancement**
Discuss the likely event of exceeding free Heroku Postgres row limit in production
![image](https://user-images.githubusercontent.com/65220389/188816956-32a2b233-42da-4ec3-92da-712d12f0c6d4.png)

**Comment by ralf-t** [comment]
scale up ng service ambagan nalang >.<
