### ISSUE TITLE
raw data

### ISSUE THREAD

**Issue by ralf-t** [Iionsroar/inquizitor#64]
### dataset_1
**columns:**
user_id 
username
question_id
action_id (not sure saang table eto stored. figured it would help if I can provide back to u anong rows yung may anomalies)
event_1 to event_n
timestamp (whatever raw format available. don't simplify)
label (cheating = 1, not cheating = 0)

Hindi to aggregated. So magiging sparse sya. Para ma examine ko rin each action hehe. Will aggregate it myself nalang sa pandas.

e.g.:
1 user1 1 5 0 0 0 0 0 0 1 XX:XX:XX 1
1 user1 1 8 0 0 0 1 0 0 0 XX:XX:XX 1
1 user2 3 3 0 0 1 0 0 0 0 XX:XX:XX 0

========================================

### dataset_2
**columns:**
user_id 
username
time_started
time_finished

re time_started and time_finished, I'm not sure kung possible yan kasi di ko tanda kung meron sa data natin niyan lol
so not sure kung mapoprovide tong dataset_2

========================================

csv format nalang hehe

**Comment by Iionsroar** [comment]
**dataset 1:** sent heroku postgres url sa discord para transparent sa sql retrieval ng data (download as csv na lang)
**dataset 2:** WIP

**Comment by ralf-t** [comment]
Wow looks good pare lookin like a proper dataset. Will tinker with dis hehe

trivial:
btw may other word ba for action sa action_id? di ko alam dapat itawag eh HAAHAHAHA pwede naman natin palitan

**Comment by Iionsroar** [comment]
> Wow looks good pare lookin like a proper dataset. Will tinker with dis hehe

eye candy results HAAHHAHA

> btw may other word ba for action sa action_id? di ko alam dapat itawag eh HAAHAHAHA pwede naman natin palitan

event_id, input_id? yan lang naiisip ko

**Comment by ralf-t** [comment]
event works hehe
