### ISSUE TITLE
Additional Details in Read Per Question Attempts Action endpoint

### ISSUE THREAD

**Issue by xtian18** [Iionsroar/inquizitor#65]
**Is your feature request related to a problem? Please describe.**
I need additional information in the /{quizzes}/quiz_index/actions-per-question (Read Per Question Attempts Action endpoint). Currently, it only returns aggregated actions per question of each student in a quiz.

**Describe the solution you'd like**
Is it possible to add the student name and score as well instead of just the student id? Also in the prototype used last semester, the time taken is included. However, I am not sure if we will retain it.

**Additional context**
Something like the Read Quiz Actions endpoint but with the score and aggregated actions.
![image](https://user-images.githubusercontent.com/58137485/197532412-29e4a05e-d926-4a55-9b12-13f30edb3f7c.png)

**Comment by Iionsroar** [comment]
![image](https://user-images.githubusercontent.com/65220389/197718579-3307ab48-f03a-46f6-9435-a8ebeb3d028a.png)
lmk if theres a better format @xtian18 

take note lang na baka need iupdate yung frontend components na nagpprocess ng return value nung updated endpoint

**Comment by Iionsroar** [comment]
tagging @xtian18 baka natabunan notif

**Comment by xtian18** [comment]
sorry. d pa ba to nadadagdag? ganun pa rin sya sakin. tsaka pala ngayon ko lang napansin, need din pala yung total item

**Comment by Iionsroar** [comment]
> d pa ba to nadadagdag?

di pa siya implemented sa main branch

> tsaka pala ngayon ko lang napansin, need din pala yung total item

ano ulit yung total item

**Comment by xtian18** [comment]
> di pa siya implemented sa main branch

aling branch gagamitin ko para matest, sa prod-commands ba?

> ano ulit yung total item

kung ano yung total points nung quiz

**Comment by Iionsroar** [comment]
pagkaadd ko nung total points ipush ko na sa main

**Comment by Iionsroar** [comment]
oks lang ba gawin kong `{'score': score/totalItem}` ?

**Comment by xtian18** [comment]
ok lang

**Comment by Iionsroar** [comment]
- done pushing sa main
- ~5 mins para magreflect sa production environment

**Comment by xtian18** [comment]
ok na, gumagana salamat
