### ISSUE TITLE
Lacking questions items???

### ISSUE THREAD

**Issue by ralf-t** [Iionsroar/inquizitor#66]
Yung actions ni manubaychazz ay kulang?

![image](https://user-images.githubusercontent.com/66364379/197571887-bd1dcef9-152b-4400-9308-b00748d6fe73.png)
**Expected behavior**
Expecting to see question ids 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

**Comment by ralf-t** [comment]
Checked the unique counts for each question_id, incomplete din yung iba

Why dis happened lmao

Expecting na 156 count for each question dahil natapos naman nila

![image](https://user-images.githubusercontent.com/66364379/197573243-980bac7d-25e6-4e65-9059-2a7d9a5d86c9.png)

**Comment by Iionsroar** [comment]
> Yung actions ni manubaychazz ay kulang?

baka naskip niya yung questions dahil sa mabilis na pagclick ng next button, macocontact ba naten siya?

**Comment by ralf-t** [comment]
Hopefully matackle natin for tomorrow's consultation waaa
